### ISSUE TITLE
Npm run dev 

### ISSUE THREAD

**Issue by vsundeept** [LloydJanseVanRensburg/mini-mern-ecommerce-project#1]
![image](https://user-images.githubusercontent.com/14179187/114776045-a770be00-9d8f-11eb-8de3-cfc55c00c52d.png)

App is loading but facing the above error. Kindly assist me

**Comment by LloydJanseVanRensburg** [comment]
This might be due to the fact that you are trying to connect to a port call '5000;' which should maby be '5000'

**Comment by vsundeept** [comment]
Many thanks for the correction. Your correct..!! That I have corrected now.
But unable to fetch from .env file if I'm creating a const and accessing it works.
Accessing through process.env.PORT or process.env.MONGO_URI it says failed.
