### ISSUE TITLE
DB connection failed

### ISSUE THREAD

**Issue by vsundeept** [LloydJanseVanRensburg/mini-mern-ecommerce-project#2]
![image](https://user-images.githubusercontent.com/14179187/114856948-53a0bc00-9e05-11eb-9213-12b86f6fa76c.png)

DB Connection failed

**Comment by LloydJanseVanRensburg** [comment]
Just make sure to move .env file into the backend folder and then at the top of the server.js add code 'require('dotenv').config()'

**Comment by vsundeept** [comment]
Thanks a lot. Issue resolved.

**Comment by harsha19980324** [comment]
I had the same problem.  The [above-mentioned](URL) solution did not solve the problem.

![image](https://user-images.githubusercontent.com/84613888/133881676-fa21e153-a473-4357-9af3-4cdbb9210510.png)
