### ISSUE TITLE
Changin The database Products

### ISSUE THREAD

**Issue by Fersi60** [LloydJanseVanRensburg/mini-mern-ecommerce-project#4]
Hi how can i change the data from the database  ? im confused ..   ? 
and thank you for this  video !

**Comment by Mr-Harsh-Singh** [comment]
> Hi how can i change the data from the database ? im confused .. ?
> and thank you for this video !
`.env`

**Comment by Fersi60** [comment]
Actually i added two functions on the backend one to add new products and two to delete the old products so  its works and im having my own products
